---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - ca-certificates
      - software-properties-common
    state: present

- name: Add Zabbix repository key
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Add Zabbix repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.4/ubuntu jammy main"
    state: present
    filename: zabbix.list

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install Zabbix server packages
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent2
    state: present

- name: Install PHP extensions
  apt:
    name:
      - php8.1
      - php8.1-mysql
      - php8.1-gd
      - php8.1-xml
      - php8.1-mbstring
      - php8.1-bcmath
      - php8.1-curl
    state: present

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Wait for MySQL to be ready
  wait_for:
    port: 3306
    delay: 10
    timeout: 120

- name: Create Zabbix database
  shell: |
    mysql -e "CREATE DATABASE IF NOT EXISTS zabbix CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
  args:
    executable: /bin/bash

- name: Create Zabbix user
  shell: |
    mysql -e "CREATE USER IF NOT EXISTS 'zabbix'@'localhost' IDENTIFIED BY '{{ mysql_zabbix_password }}';"
    mysql -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';"
    mysql -e "FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash

- name: Import Zabbix database schema
  shell: |
    zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql -u zabbix -p{{ mysql_zabbix_password }} zabbix
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Configure Zabbix server
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- name: Configure Nginx for Zabbix
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/zabbix
  notify: restart nginx

- name: Enable Zabbix site in Nginx
  file:
    src: /etc/nginx/sites-available/zabbix
    dest: /etc/nginx/sites-enabled/zabbix
    state: link
  notify: restart nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Ensure runtime directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  loop:
    - /run/zabbix
    - /var/run/zabbix

- name: Ensure log directory exists
  file:
    path: /var/log/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent2
    - nginx
    - mysql
