---
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Elasticsearch GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: elasticsearch

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Ensure Elasticsearch directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'
  loop:
    - /etc/elasticsearch
    - /var/lib/elasticsearch
    - /var/log/elasticsearch

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0640'
  notify: restart elasticsearch

- name: Configure JVM options
  copy:
    content: |
      -Xms512m
      -Xmx512m
    dest: /etc/elasticsearch/jvm.options.d/heap.options
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
  notify: restart elasticsearch

- name: Start and enable Elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for Elasticsearch to start
  wait_for:
    port: 9200
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 120

- name: Check Elasticsearch status
  uri:
    url: "http://localhost:9200"
    method: GET
    status_code: 200
  register: es_status
  until: es_status.status == 200
  retries: 10
  delay: 5
