---
- name: Setup Elasticsearch (simple)
  hosts: elasticsearch.ru-central1.internal
  become: yes
  
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Add Elasticsearch GPG key
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present
        filename: elasticsearch

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: Configure Elasticsearch
      copy:
        content: |
          cluster.name: diplom-cluster
          node.name: {{ ansible_hostname }}
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          xpack.security.enabled: false
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: '0640'

    - name: Configure JVM options
      copy:
        content: |
          -Xms512m
          -Xmx512m
        dest: /etc/elasticsearch/jvm.options.d/heap.options
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'

    - name: Start and enable Elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for Elasticsearch to start
      wait_for:
        port: 9200
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 180

    - name: Check Elasticsearch status
      shell: |
        curl -s -o /dev/null -w "%{http_code}" http://localhost:9200/
      register: es_status
      until: es_status.stdout == "200"
      retries: 15
      delay: 5

    - name: Show Elasticsearch info
      shell: |
        curl -s http://localhost:9200/ | grep -E '"name"|"cluster_name"|"version"'
      register: es_info

    - name: Display Elasticsearch status
      debug:
        msg: "Elasticsearch started successfully: {{ es_info.stdout }}"
