---
- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - ca-certificates
    state: present

- name: Add Zabbix repository key
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Add Zabbix repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.4/ubuntu jammy main"
    state: present
    filename: zabbix.list

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install Zabbix Agent
  apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix Agent
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
  notify: restart zabbix-agent

- name: Enable and start Zabbix Agent
  service:
    name: zabbix-agent2
    state: started
    enabled: yes
